controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - slider
    interface_name: position, velocity, acceleration
    command_interfaces:
      - acceleration
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
